if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

export HOMEBREW_NO_AUTO_UPDATE=1

# Power10K stuff
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export PATH="/opt/homebrew/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:$PATH"


bindkey '^ ' autosuggest-accept

# eza ls setup
alias ls="eza --icons=always"

# zoxide cd setup
eval "$(zoxide init zsh)"
alias cd="z"

# Jankey Borders
alias jankey="brew services start borders"

# SSH 
alias ssh-ubc="ssh kori0909@remote.students.cs.ubc.ca"
alias ssh-server1="ssh server@100.65.10.64"
alias ssh-server2="ssh server@100.80.160.74"
alias ssh-azure0="ssh azureuser@20.151.59.61"

# Python Alias
alias venv="python3 -m venv ."
alias zr="source ~/.zshrc"
alias s="source" 

# Mac Alias
alias alttab="pkill AltTab; screen -dmS AltTab /Applications/AltTab.app/Contents/MacOS/AltTab"
alias wake-desktop="wakeonlan -i 192.168.8.174 04:7C:16:D1:B2:79"
alias quit-moonlight="echo ctrl+shft+alt+q"

#Brew Alias
alias bi="brew install"
alias bl="brew list"

# pnpm Alias
alias pn="pnpm"
alias pni="pnpm install"

# Quick Access
alias vi="nvim"
alias ali="nvim ~/.config/shell/zshrc"
alias nvim-config="nvim ~/.config/nvim"
alias lvsr="live-server"
alias nwfox="open -n /System/Volumes/Data/Applications/Firefox.app"
alias aerospace-config="nvim ~/.config/aerospace/aerospace.toml"

# GCC/Clang
alias c="clear"
alias gcc="gcc-14"
alias g++="g++-14"
alias g++o="g++-14 -o"

#Git Alias
alias ga="git add"
alias gc="git commit -m "
alias gp="git push"
alias gpll="git pull origin main"
alias gs="git status"

# GitHub Alias
alias ghgc="gh gist create"
alias ghgl="gh gist list"
alias ghge="gh gist edit"
alias ghgv="gh gist view"
alias ghg-clone="gh gist clone"
alias ghgd="gh gist delete"

# Kubernetes
alias k="kubectl"

# Functions
GitLazyPush() {
  if [ -z "$1" ]; then
    echo "Error: Commit message is required"
    return 1
  fi

  git add .
  git commit -m "$1"
  git push
}

function tmux-local() {
  if tmux has-session -t local 2>/dev/null; then
    tmux attach-session -t local
  else
    tmux new-session -s local
  fi
}

function tmux-ssh() {
  if tmux has-session -t ssh 2>/dev/null; then
    tmux attach-session -t ssh
  else
    tmux new-session -s ssh
  fi
}
