if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Powerlevel 10K stuff
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export DENO_INSTALL="/Users/kori0909/.deno"
export PATH="/opt/homebrew/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:$DENO_INSTALL/bin:$PATH"
# eza ls setup
alias ls="eza --icons=always"

# zoxide cd setup
eval "$(zoxide init zsh)"
alias cd="z"

# Python Alias
alias venv="python3 -m venv ."
alias zr="source ~/.zshrc"
alias s="source" 

# Mac Alias
alias alttab="pkill AltTab; screen -dmS AltTab /Applications/AltTab.app/Contents/MacOS/AltTab"
alias homeserver="ssh server@home-server.ibex-puffin.ts.net"
alias wake-desktop="wakeonlan -i 192.168.8.174 04:7C:16:D1:B2:79"
alias quit-moonlight="echo ctrl+shft+alt+q"

#Brew Alias
alias bi="brew install"
alias bs="brew list"
alias pn="pnpm"
alias pni="pnpm install"
alias vi="nvim"
alias ali="nvim ~/.zshrc"
alias nvimconf="nvim ~/.config/nvim"
alias lvsr="live-server"
alias nwfox="open -n /System/Volumes/Data/Applications/Firefox.app"
alias bi="brew install"
alias bl="brew list"
alias c="clear"
alias gc="gcc-14"
alias g+="g++-14"
alias g+c="g++-14 -o"

# Git Alias
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
